### ISSUE TITLE
Any ideas on how to use it with Zustand?

### ISSUE THREAD

**Issue by rzfzr** [matt-oakes/redux-devtools-expo-dev-plugin#11]
I can see that many redux dev tools work out of the box with zustand, however, I can't figure out how to do the initial setup for this one, as I am used to using middlewares but not enhancers.
Any ideas?
Thanks

**Comment by matt-oakes** [comment]
I don't have experience with Zustand so I can't say for sure but unfortunatly I don't beleive that it would be possible to use as it does not have an enhancer system. It does seem to have a [`devTools` integration itself](https://github.com/pmndrs/zustand/blob/main/src/middleware/devtools.ts) though so maybe it's possible. You'll likely need to use part of that and hook it up to the Expo devtools client plugin instance [as I've done here for Redux](https://github.com/matt-oakes/redux-devtools-expo-dev-plugin/blob/main/src/devtools.ts).

It's not something I'm likely to support in this repo, but feel free to use it as a base for your own Expo devtools plugin.

**Comment by rzfzr** [comment]
It does have devTools integration, but it seems not to be working with hermes for now.
Thanks, I'll take a look into it.

**Comment by oller** [comment]
Just a bump on this. Am looking at this issue now. How much lift do we suspect to be able to support zustand with this, as the native zustand devtools middleware does.

**Comment by kamlesh-tp** [comment]
Made one that works with browser devtools. Hope it helps https://github.com/jhonny1525/zustand-expo-devtools

**Comment by matt-oakes** [comment]
Great work!
