### ISSUE TITLE
Doesnt' work for expo <52

### ISSUE THREAD

**Issue by Brandon-Perry** [matt-oakes/redux-devtools-expo-dev-plugin#18]
I tried using the instructions to add this to my project using expo 51, but the devtool would not link to my project despite the ip/port being correct. I upgraded however and it worked just fine. I wanted to add an issue here so that either its fixed or, if support for previous versions is being dropped for the new architecture, that some note of that gets added to the README.

Thanks!

**Comment by matt-oakes** [comment]
The peer dependency on this module should stop you installing v1.0.0 if you don't have Expo 52. Using npm I believe you'd need to manually force it to install and ignore the warning. I believe that Yarn is more permissive and just prints a warning.

I have added a note in the release to let users know they should continue to use the previous version if they haven't upgraded Expo yet.
