### ISSUE TITLE
Update README for RTK

### ISSUE THREAD

**Issue by theogravity** [matt-oakes/redux-devtools-expo-dev-plugin#4]
See discussion here:

https://github.com/reduxjs/redux-devtools/issues/1533#issuecomment-2146390042

**Comment by matt-oakes** [comment]
Thanks. This is on my list to look into. 

That snippet will work for most Redux toolkit users, but I have a feeling it will lead to issues for Redux Saga users.

They might not be able to see actions that have been dispatched from a saga. I think that to resolve this we need to export two different middlewares, one for the start and one for the end. Its still on my list to look into though. 

If you’ve tried this and it’s working then let me know.
